# Generated by Django 5.2.6 on 2025-10-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(unique=True, verbose_name='URL идентификатор')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена'), ('draft', 'Черновик')], default='draft', max_length=10, verbose_name='Статус')),
                ('channel_username', models.CharField(default='@test_channel', max_length=100, verbose_name='Username канала')),
                ('welcome_text', models.TextField(default='Добро пожаловать!', verbose_name='Приветственный текст')),
                ('button_text', models.CharField(default='Участвовать', max_length=50, verbose_name='Текст кнопки')),
                ('theme_color', models.CharField(default='#FF6B35', max_length=7, verbose_name='Цвет темы')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='ID пользователя Telegram')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписан на канал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'telegram_id')},
            },
        ),
    ]
