# Generated by Django 5.2.6 on 2025-10-02 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_message',
            field=models.TextField(default='Добро пожаловать на мероприятие! Нажмите кнопку ниже чтобы участвовать в розыгрыше.', verbose_name='Первое сообщение бота'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='button_text',
            field=models.CharField(default='🎯 Участвовать в розыгрыше', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='welcome_text',
            field=models.TextField(default='Добро пожаловать!', verbose_name='Текст приветствия'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.campaign', verbose_name='Мероприятие'),
        ),
    ]
