# Generated by Django 5.2.6 on 2025-10-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bot_is_running',
            field=models.BooleanField(default=False, verbose_name='Бот запущен'),
        ),
    ]
