# Generated by Django 5.2.6 on 2025-10-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_bot_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='conditions_button',
            field=models.CharField(default='📋 Условия розыгрыша', max_length=50, verbose_name='Текст кнопки "Условия"'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='conditions_text',
            field=models.TextField(default='Для участия в розыгрыше необходимо:\n• Быть подписанным на наш канал\n• Заполнить контактные данные\n• Согласиться на обработку персональных данных', verbose_name='Текст условий акции'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prizes_button',
            field=models.CharField(default='🎁 Посмотреть призы', max_length=50, verbose_name='Текст кнопки "Призы"'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prizes_text',
            field=models.TextField(default='🏆 Главные призы:\n• Профессиональный графический планшет\n• Набор дизайнерских инструментов\n• Годовой курс по дизайну', verbose_name='Текст призов'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='share_phone_button',
            field=models.CharField(default='📱 Поделиться номером', max_length=50, verbose_name='Текст кнопки "Поделиться номером"'),
        ),
    ]
