# Generated by Django 5.2.6 on 2025-10-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_conditions_button_campaign_conditions_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel_username',
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel_usernames',
            field=models.TextField(default='@test_channel', help_text='Укажите usernames каналов через запятую, например: @channel1, @channel2', verbose_name='Usernames каналов (через запятую)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='raffle_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата розыгрыша'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='winners',
            field=models.JSONField(blank=True, default=list, verbose_name='Победители'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='winners_count',
            field=models.IntegerField(default=1, verbose_name='Количество победителей'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('finished', 'Завершено'), ('raffled', 'Розыгрыш проведен')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
