# Generated by Django 5.2.6 on 2025-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaign_channel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='registration_stage',
            field=models.CharField(choices=[('start', 'Начало'), ('name', 'Ввод имени'), ('phone', 'Ввод телефона'), ('subscription', 'Проверка подписки'), ('completed', 'Завершено')], default='start', max_length=20, verbose_name='Стадия регистрации'),
        ),
    ]
